### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/AdobeAnalytics#1]
Hey Andy - 

Starting a repo, successful first step! Although I presume your code works, I haven't tested it yet.

Here are some ideas for the next set of changes:

#### Current Code:
- [x] The `sha` module is deprecated, so switch to `hashlib` instead. You should probably use the `requests` library as well, instead of `urllib2`, as requests is newer and made to be more reasonably easy to use
- [x] Even though the user will be providing their username and shared_secret, I think these should be private attributes by default. Use two leading underscores to "hide" a variable inside a class. 
- [x] By convention, follow the PEP-8 style guide. Make the `adobeanalytics` class `AdobeAnalytics` instead. https://www.python.org/dev/peps/pep-0008/#class-names
- [x] Make a fully-installable package before getting started. The package would be named `adobeanalytics` or similar, then your class would be `AdobeAnalytics`, so that users would type 

```python
from adobeanalytics import AdobeAnalytics
```

#### Future Code

In general, your code would work, but I suggest you think about any functions or methods as a single unit that do one thing. So the workflow of an API call would be something like the following:

1. User creates `AdobeAnalytics` object as the following:
```python 
aa = AdobeAnalytics(user_name = , shared_secret= )
```

The result of this should NOT return anything to stdout; my R version is a hack, because it's not clear anything happens because I don't assign anything in the global namespace per CRAN rules, so I print a message out to show the user something happens. That's not necessary in Python, because the `aa` object will exist globally.

As part of the __init__ process, you should allow the user to specify their endpoint; additionally, should the user not specify an endpoint, you should call `GetEndpoint` from the Adobe API to find out what endpoint someone is using

2. With the `aa` object available, users will now call all methods from here. Although PEP8 states that methods should be lower case or lowercase with underscores, my opinion is that you should follow the Adobe convention of CamelCase. So users would call methods such as `aa.GetReportSuites()` to get their list of report suites

3. For each API call, break up the flow into the following:

- User specifies arguments to method
- method converts arguments to JSON call
- method makes API call
- method receives response (either report_id or immediate response)
- If method receives a report_id, then need to repeatedly check to see if report is ready. If API call returns immediately, you'll get JSON back
- Eventually, the report is ready, and you have JSON

4. At this point, returning JSON as a Python Dict should be a valid state. Python users are used to this, whereas in R, I force everything to a data frame because there are no dicts in R and users are more used to dataframes.

5. Write dataframe parsers :) Even though the Adobe JSON is horrid, it's mostly possible to return a data frame without much effort. At first, this should probably be a method, but it could be a keyword argument eventually in a method call (so that people can specifiy getting a Dict or pandas Data Frame back)

Of course, this is very high level, so feel free to ask questions as you go along. I'll be able to contribute code to this as well, since I want a Python library myself; just let me know what you are working on so we don't duplicate effort.

**Comment by randyzwitch** [comment]
When we write the dataframe parsers, this will likely be a well-loved function:

http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.io.json.json_normalize.html

**Comment by andymaheshw** [comment]
Awesome! Thank you for sending these over. I will get on it.

Andy

**Comment by andymaheshw** [comment]
I just use:  df = pd.DataFrame.from_dict(result_js['report']['data'],
orient='columns', dtype=None)

for the parsing. It's pretty easy to use this, and it comes out nearly
perfect (misses a few additional fields like the suite and segments).

Andy

**Comment by randyzwitch** [comment]
I think you’re going to really be surprised once you get into it ;)

**Comment by andymaheshw** [comment]
Hi Randy,

Worked on the code a bit tonight, still refining it. I'm still working on
changing from sha to hashlib, will have that done soon. Code should work.

I'll have a lot more free time this week, so will start getting a bunch of
methods up. I'll send over a list tomorrow and we can divide it up?

I added a __init__.py file to make it a package. Let me know if I should
add anything else.

Andy

**Comment by randyzwitch** [comment]
Great, looking forward to testing it out.

**Comment by andymaheshw** [comment]
Hi Randy,

Got back to the project today. I've fixed the method, validated it with
Company.GetReportSuites which requires validation. I'm in a good spot in
terms of the main engine. Since you have so much already written in R, I'm
working on making it python compatible.

Let me know how we should split the files up - I noticed the R one is split
neatly on methods. Should I put omni_api into the parent class and then
start building child classes that inherit along the API names? The methods
could tie to the API and inherit everything or overload the methods. I
noticed you incremented the counter for RSiteCatalyst.

I have more time now to focus on this, so let me know and I will keep
building it out.

Andy

**Comment by randyzwitch** [comment]
Sorry for not getting back to you sooner, but I wanted to really make sure the code you were writing was a good base to start from.

I just merged in two commits which cleans up your code and makes it more "Pythonic". From now on, I'll make a branch and do pull requests, I forgot I was a contributor on this repo :)

The basic thing to take away from these changes is making sure that a function only does one thing (I split your `omni_api` function into a header function and a call function), as well as **kwargs, which is a special Python convention. You don't need to specify empty dictionaries everywhere, **kwargs automatically collects any keyword arguments passed to the function into a dictionary called `kwargs`. This is developer convenience, but requires writing good documentation on the allowable types, since users cannot read the source to understand what arguments are possible.

Take a look at the code, let me know if you have any questions. I commented out the `Run` function for now, as I think we should just focus on the methods that return immediately. If you try hard, I bet it's possible to write code that abstracts the `GetReportSuites` function and generates 10-20 functions for all the `GetSegments`, `GetEvents` variables and so on. This is called metaprogramming, I'll let you research that on your own.

**Comment by randyzwitch** [comment]
Just realized my commit has made a mess of the code. The commit works, but future code I wrote is inelegant. So now it's up to me to fix I guess!

Will work on this tonight/tomorrow, get everything working correctly.

**Comment by andymaheshw** [comment]
no problem, I'll branch off from the code on my local. I'm still digging
into metaprogramming haha.

Thanks for all the tips, do you have any books/sites that can help me get
better at python features like kwargs? I researched effective python today
so I was going to try to read it as fast as possible.


Andy

**Comment by randyzwitch** [comment]
Take a look at the pull request #2 I just submitted, which I think fixes the problems I saw before. For the most part, everything should be a POST request; things weren't working because I didn't notice that you had developed the GET request portion only.

In terms of getting better at some of the obscure features, they are just something you pick up along the way. There's really only a handful of obscure features, which can be Googled: generators, decorators, list comprehensions, varargs (which is what *args and **kwargs are). I'll introduce them wherever they make sense, and just point them out where you don't understand (pull requests let you hit a + sign on a line and make a comment)

Good luck. Let me know if you want to fill in all these function stubs or if you want help.

**Comment by andymaheshw** [comment]
Hi Randy, finally got back to this after a break. Let me know if I did the cancel method right (should it iterate across multiple rsid's?) Thanks.

**Comment by andymaheshw** [comment]
I will also keep working to finish up the methods, I'm using RSiteCatalyst as a guide so I'll try to speed up development going forward. My goal is all done by end May. Ambitious, but I think I can do it!

**Comment by andymaheshw** [comment]
Randy, what methods are left? By my count:
JsonQueueRealTimeReport - Report.Run
SubmitJsonQueueReport - Report.Queue
ValidateReport - Report.Validate

All the Get* methods I checked ran just fine, unless there's something I'm missing. Do you mean we need an error handling system like your R code?

**Comment by randyzwitch** [comment]
I'll try and take a look at this tonight or tomorrow, I've been in the process of moving and have been in a state of disorganization :)

**Comment by randyzwitch** [comment]
Let's close this and create discrete issues, so that each of us can claim various functionality
